### ISSUE TITLE
Usar reproducción proporcional al fitness

### ISSUE THREAD

**Issue by JJ** [erseco/moving_target_defense#3]
No tengo muy claro el proceso de selección que se usa, pero me da la impresión de que la probabilidad de reproducción no depende del fitness. Generalmente, no es una forma buena de explorar el espacio de búsqueda, porque van a aparecer con la misma probabilidad en el pool reproductivo todos los individuos por encima de un fitness determinado.

**Comment by erseco** [comment]
El fitness da un valor discreto proporcionado por ZAP, que son el numero de vulnerabilidades, y si hubiera una configuración incorrecta, que el comando `nginx -t` declara como emergencia el fitness sería de 999, el algoritmo va seleccionando para cruzar a los individuos que menor valor tienen, pues al tener menos vulnerabilidades tienen (segun ZAP)
